# Generated by Django 2.2.3 on 2020-02-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_pageadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAdmin',
        ),
    ]
