# Generated by Django 2.2.3 on 2020-02-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_delete_pageadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
